### ISSUE TITLE
Stimela build error "FROM stimela/rfinder:1.0.1 - Pillow upgrade"

### ISSUE THREAD

**Issue by lucianbotha** [SpheMakh/Stimela#377] opened 2019-05-03 07:21 UTC
Running: docker build --force-rm -f /tmp/tmpu2GimD/tmpJNme8E -t dante_cab/rfinder /tmp/tmpu2GimD
Sending build context to Docker daemon  16.38kB
Step 1/13 : FROM stimela/rfinder:1.0.1
 ---> 7e50e3c54c87
Step 2/13 : MAINTAINER <sphemakh@gmial.com>
 ---> Using cache
 ---> fbda37952cc3
Step 3/13 : RUN pip install pillow --upgrade
 ---> Running in 3db2238c6101
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Pyt
hon 2.7.
Collecting pillow
  Downloading https://files.pythonhosted.org/packages/b6/4b/5adc1109908266554fb978154c797c7d71aba43dd15508d8c1565648f6bc/Pillow-6.0.0-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
Installing collected packages: pillow
  Found existing installation: Pillow 5.4.1
    Uninstalling Pillow-5.4.1:
      Successfully uninstalled Pillow-5.4.1
Could not install packages due to an EnvironmentError: [Errno 16] Device or resource busy: '/usr/local/lib/python2.7/dist-packages/~IL/.nfs00000000800a145d000003ca'

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 437, in run
    wheel_cache.cleanup()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py", line 60, in __exit__
    self.cleanup()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py", line 83, in cleanup
    rmtree(self.path)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line 121, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/tmp/pip-install-LYT9os/pillow/PIL/.nfs00000000800a146e00000493'
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 3db2238c6101
The command '/bin/sh -c pip install pillow --upgrade' returned a non-zero code: 2

**Comment by SpheMakh** [comment] 2019-05-03 13:48
@Athanaseus any idea what is causing this failure (its from rfinder)?

**Comment by SpheMakh** [comment] 2019-05-05 14:16
@lucianbotha this should be fixed in the master branch. Please do this to get the fix

```
pip install --upgrade git+https://github.com/SpheMakh/Stimela
docker pull stimela/rfinder:1.0.1
stimela build --no-cache
```

**If you are working in a virtual environment, activate it first**

**Comment by SpheMakh** [comment] 2019-05-05 14:17
Please let us know if the fix works for you

**Comment by lucianbotha** [comment] 2019-05-06 07:53
Hi

I got a little bit further but then it failed again with the following
error.

error: [Errno 39] Directory not empty:
'build/bdist.linux-x86_64/wheel/PyYAML-5.1.dist-info'


  ----------------------------------------

  Failed building wheel for pyyaml

  Running setup.py clean for pyyaml

Failed to build pyyaml

Installing collected packages: pyyaml

  Running setup.py install for pyyaml: started

    Running setup.py install for pyyaml: finished with status 'done'

Could not install packages due to an EnvironmentError: [Errno 16] Device or
resource busy:
'/tmp/pip-install-CdMx9B/pyyaml/tests/lib3/.nfs00000000800b4cea000008a6'


Exception:

Traceback (most recent call last):

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py",
line 143, in main

    status = self.run(options, args)

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py",
line 410, in run

    wheel_cache.cleanup()

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py",
line 58, in __exit__

    self.cleanup()

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py",
line 81, in cleanup

    rmtree(self.path)

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 49, in wrapped_f

    return Retrying(*dargs, **dkw).call(f, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 212, in call

    raise attempt.get()

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 247, in get

    six.reraise(self.value[0], self.value[1], self.value[2])

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 200, in call

    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line
111, in rmtree

    onerror=rmtree_errorhandler)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree

    onerror(os.remove, fullname, sys.exc_info())

  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree

    os.remove(fullname)

OSError: [Errno 16] Device or resource busy:
'/tmp/pip-install-CdMx9B/pyyaml/tests/lib3/.nfs00000000800b4cea000008a6'

You are using pip version 18.1, however version 19.1 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

Removing intermediate container ed6b5eee716c

The command '/bin/sh -c pip install pyyaml' returned a non-zero code: 2


Traceback (most recent call last):

  File "/home/dante/ddfenv/bin/stimela", line 13, in <module>

    stimela.main([a for a in sys.argv[1:]])

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 634, in main

    _cmd(argv)

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 175, in build

    build_args=build_args, args=no_cache)

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/docker.py",
line 41, in build

    bdir])

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/utils/__init__.py",
line 110, in xrun

    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command,
process.returncode))

stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 2

**Comment by SpheMakh** [comment] 2019-05-06 09:21
It's hard to make out what's going wrong. Please do the following:

1. Post the Operating system and distribution you are using,
2. the Docker version, 
3. the command you ran to get this error.
4. Post the full error. Use backquotes when posting the terminal output.

Example,  The result of 

\`\`\` 

Failed building wheel for pyyaml

  Running setup.py clean for pyyaml

Failed to build pyyaml

Installing collected packages: pyyaml

  Running setup.py install for pyyaml: started

    Running setup.py install for pyyaml: finished with status 'done'

Could not install packages due to an EnvironmentError: [Errno 16] Device or
resource busy:
'/tmp/pip-install-CdMx9B/pyyaml/tests/lib3/.nfs00000000800b4cea000008a6'

\`\`\`

is

``` 
Failed building wheel for pyyaml

  Running setup.py clean for pyyaml

Failed to build pyyaml

Installing collected packages: pyyaml

  Running setup.py install for pyyaml: started

    Running setup.py install for pyyaml: finished with status 'done'

Could not install packages due to an EnvironmentError: [Errno 16] Device or
resource busy:
'/tmp/pip-install-CdMx9B/pyyaml/tests/lib3/.nfs00000000800b4cea000008a6'

 ```

Which is a bit easier to read

**Comment by lucianbotha** [comment] 2019-05-06 10:38
Hi

*Operating System:* Ubuntu 14.04 LTS
*Docker Version:* 18.06.1-ce build e68fc7a
*Command:* stimela build --no-cache

I hope this is readable. I tried the backticks like you have in the example
above.

```

Running: docker build --no-cache --force-rm -f /tmp/tmpJjknfZ/tmp2uhd5T -t
dante_cab/ddfacet /tmp/tmpJjknfZ

Sending build context to Docker daemon  52.74kB

Step 1/11 : FROM stimela/ddfacet:1.0.1

 ---> 47939eefe2cc

Step 2/11 : MAINTAINER <sphemakh@gmail.com>

 ---> Running in 57e78232a30b

Removing intermediate container 57e78232a30b

 ---> d96d7fa95ba9

Step 3/11 : RUN pip install pyyaml

 ---> Running in 241bb4143419

Collecting pyyaml

  Downloading
https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
(274kB)

Building wheels for collected packages: pyyaml

  Running setup.py bdist_wheel for pyyaml: started

  Running setup.py bdist_wheel for pyyaml: finished with status 'error'

  Complete output from command /usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-install-ZySNTb/pyyaml/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/tmp/pip-wheel-u5CDG3 --python-tag cp27

  running bdist_wheel

  running build

  running build_py

  creating build

  creating build/lib.linux-x86_64-2.7

  creating build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/cyaml.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/scanner.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/tokens.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/nodes.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/composer.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/dumper.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/serializer.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/emitter.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/constructor.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/representer.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/resolver.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/error.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/events.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/loader.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/__init__.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/parser.py -> build/lib.linux-x86_64-2.7/yaml

  copying lib/yaml/reader.py -> build/lib.linux-x86_64-2.7/yaml

  running build_ext

  skipping 'ext/_yaml.c' Cython extension (up-to-date)

  building '_yaml' extension

  creating build/temp.linux-x86_64-2.7

  creating build/temp.linux-x86_64-2.7/ext

  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g
-fstack-protector-strong -Wformat -Werror=format-security -fPIC
-I/usr/include/python2.7 -c ext/_yaml.c -o
build/temp.linux-x86_64-2.7/ext/_yaml.o

*  In file included from ext/_yaml.c:591:0:*

*  ext/_yaml.h:2:18: fatal error: yaml.h: No such file or directory*

  compilation terminated.

  Error compiling module, falling back to pure Python

  installing to build/bdist.linux-x86_64/wheel

  running install

  running install_lib

  creating build/bdist.linux-x86_64

  creating build/bdist.linux-x86_64/wheel

  creating build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/cyaml.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/scanner.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/tokens.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/nodes.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/composer.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/dumper.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/serializer.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/emitter.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/constructor.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/representer.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/resolver.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/error.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/events.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/loader.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/__init__.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/parser.py ->
build/bdist.linux-x86_64/wheel/yaml

  copying build/lib.linux-x86_64-2.7/yaml/reader.py ->
build/bdist.linux-x86_64/wheel/yaml

  running install_egg_info

  running egg_info

  creating lib/PyYAML.egg-info

  writing lib/PyYAML.egg-info/PKG-INFO

  writing top-level names to lib/PyYAML.egg-info/top_level.txt

  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt

  writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'

  reading manifest file 'lib/PyYAML.egg-info/SOURCES.txt'

  writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'

  Copying lib/PyYAML.egg-info to
build/bdist.linux-x86_64/wheel/PyYAML-5.1-py2.7.egg-info

  running install_scripts

  creating build/bdist.linux-x86_64/wheel/PyYAML-5.1.dist-info/WHEEL

  creating '/tmp/pip-wheel-u5CDG3/PyYAML-5.1-cp27-cp27mu-linux_x86_64.whl'
and adding '.' to it

  adding 'yaml/__init__.py'

  adding 'yaml/composer.py'

  adding 'yaml/constructor.py'

  adding 'yaml/cyaml.py'

  adding 'yaml/dumper.py'

  adding 'yaml/emitter.py'

  adding 'yaml/error.py'

  adding 'yaml/events.py'

  adding 'yaml/loader.py'

  adding 'yaml/nodes.py'

  adding 'yaml/parser.py'

  adding 'yaml/reader.py'

  adding 'yaml/representer.py'

  adding 'yaml/resolver.py'

  adding 'yaml/scanner.py'

  adding 'yaml/serializer.py'

  adding 'yaml/tokens.py'

  adding 'PyYAML-5.1.dist-info/LICENSE.txt'

  adding 'PyYAML-5.1.dist-info/top_level.txt'

  adding 'PyYAML-5.1.dist-info/WHEEL'

  adding 'PyYAML-5.1.dist-info/METADATA'

  adding 'PyYAML-5.1.dist-info/RECORD'

  removing build/bdist.linux-x86_64/wheel

error: [Errno 39] Directory not empty:
'build/bdist.linux-x86_64/wheel/PyYAML-5.1.dist-info'


  ----------------------------------------

  Running setup.py clean for pyyaml

  Failed building wheel for pyyaml

Failed to build pyyaml

Installing collected packages: pyyaml

  Running setup.py install for pyyaml: started

    Running setup.py install for pyyaml: finished with status 'done'

Could not install packages due to an EnvironmentError: [Errno 16] Device or
resource busy:
'/tmp/pip-install-mZ38Is/pyyaml/tests/lib3/.nfs00000000800bca49000010c5'


Exception:

Traceback (most recent call last):

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py",
line 143, in main

    status = self.run(options, args)

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py",
line 410, in run

    wheel_cache.cleanup()

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py",
line 58, in __exit__

    self.cleanup()

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py",
line 81, in cleanup

    rmtree(self.path)

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 49, in wrapped_f

    return Retrying(*dargs, **dkw).call(f, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 212, in call

    raise attempt.get()

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 247, in get

    six.reraise(self.value[0], self.value[1], self.value[2])

  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py",
line 200, in call

    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

  File
"/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line
111, in rmtree

    onerror=rmtree_errorhandler)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree

    onerror(os.remove, fullname, sys.exc_info())

  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree

    os.remove(fullname)

OSError: [Errno 16] Device or resource busy:
'/tmp/pip-install-mZ38Is/pyyaml/tests/lib3/.nfs00000000800bca49000010c5'

You are using pip version 18.1, however version 19.1 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

Removing intermediate container a9f7d2620aed

The command '/bin/sh -c pip install pyyaml' returned a non-zero code: 2


Traceback (most recent call last):

  File "/home/dante/ddfenv/bin/stimela", line 13, in <module>

    stimela.main([a for a in sys.argv[1:]])

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 634, in main

    _cmd(argv)

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 175, in build

    build_args=build_args, args=no_cache)

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/docker.py",
line 41, in build

    bdir])

  File
"/home/dante/ddfenv/local/lib/python2.7/site-packages/stimela/utils/__init__.py",
line 110, in xrun

    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command,
process.returncode))

stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 2


````


Regards,

Lucian

**Comment by SpheMakh** [comment] 2019-05-06 13:52
I'm not able to reproduce these errors, but it seems that your docker is not able install pyyaml in the images. I've moved the installation to the base image. Could you please run these commands 

```
pip install --upgrade git+https://github.com/SpheMakh/Stimela@issue-377
docker pull stimela/ddfacet:1.0.3
stimela build --no-cache
```

**Comment by lucianbotha** [comment] 2019-05-07 06:00
Thanks that worked, the build was successful after the last pull.

**Comment by SpheMakh** [comment] 2019-05-07 12:21
Thanks for the feedback.

**Closed by SpheMakh** 2019-05-07 12:21 UTC
